Added a dependency check job for each pipeline to detect High Severity CVEs

diff --git a/.github/workflows/front-end-ci.yaml b/.github/workflows/front-end-ci.yaml
--- a/.github/workflows/front-end-ci.yaml
+++ b/.github/workflows/front-end-ci.yaml
@@ -33,6 +33,17 @@ jobs:
           cd front-end
           npm run lint
 
+      - name: Dependency Check
+        run: |
+          npm audit --json > audit.json
+          # Check if any high severity vulnerabilities are found
+          if grep -q '"severity":"high"' audit.json; then
+            echo "High severity vulnerabilities found!"
+            exit 1  # Fail the workflow
+          else
+            echo "No high severity vulnerabilities found"
+          fi
+
       - name: Unit Testing
         run: |
           cd front-end
